<?php
// auto-generated by sfRoutingConfigHandler
// date: 2017/08/31 17:11:31
$routes = sfRouting::getInstance();
$routes->setRoutes(
array (
  'categoryList' => 
  array (
    0 => '/categorylist/:parent/:fname/:sort/:page',
    1 => '#^/categorylist(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'parent',
      1 => 'fname',
      2 => 'sort',
      3 => 'page',
    ),
    3 => 
    array (
      'parent' => 1,
      'fname' => 1,
      'sort' => 1,
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'category',
      'action' => 'list',
      'page' => 1,
      'sort' => 'default',
      'fname' => 'music',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'categorySearch' => 
  array (
    0 => '/findalbum/:type/:find/:sort/:page',
    1 => '#^/findalbum(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'type',
      1 => 'find',
      2 => 'sort',
      3 => 'page',
    ),
    3 => 
    array (
      'type' => 1,
      'find' => 1,
      'sort' => 1,
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'category',
      'action' => 'search',
      'page' => 1,
      'sort' => 'default',
      'type' => 'find',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'filesList' => 
  array (
    0 => '/filelist/:parent/:fname/:sort/:page',
    1 => '#^/filelist(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'parent',
      1 => 'fname',
      2 => 'sort',
      3 => 'page',
    ),
    3 => 
    array (
      'parent' => 1,
      'fname' => 1,
      'sort' => 1,
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'files',
      'action' => 'list',
      'sort' => 'new2old',
      'fname' => 'music',
      'page' => 1,
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'filesShow' => 
  array (
    0 => '/download/:id/:name',
    1 => '#^/download(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'id',
      1 => 'name',
    ),
    3 => 
    array (
      'id' => 1,
      'name' => 1,
    ),
    4 => 
    array (
      'module' => 'files',
      'action' => 'show',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'filesSingerList' => 
  array (
    0 => '/singer/:singer/:sort/:page',
    1 => '#^/singer(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'singer',
      1 => 'sort',
      2 => 'page',
    ),
    3 => 
    array (
      'singer' => 1,
      'sort' => 1,
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'files',
      'action' => 'singer',
      'sort' => 'new2old',
      'page' => 1,
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'artistList' => 
  array (
    0 => '/singerlist/:page',
    1 => '#^/singerlist(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'page',
    ),
    3 => 
    array (
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'artist',
      'action' => 'list',
      'page' => 1,
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'artistList2' => 
  array (
    0 => '/singerlist/:type/:find/:page',
    1 => '#^/singerlist(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'type',
      1 => 'find',
      2 => 'page',
    ),
    3 => 
    array (
      'type' => 1,
      'find' => 1,
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'artist',
      'action' => 'list',
      'page' => 1,
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'lastAddedFiles' => 
  array (
    0 => '/newitems/:page',
    1 => '#^/newitems(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'page',
    ),
    3 => 
    array (
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'files',
      'action' => 'lastadded',
      'page' => 1,
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'featured' => 
  array (
    0 => '/featured/:page',
    1 => '#^/featured(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'page',
    ),
    3 => 
    array (
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'files',
      'action' => 'featured',
      'page' => 1,
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'topFiles' => 
  array (
    0 => '/topdownload/:type',
    1 => '#^/topdownload(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'type',
    ),
    3 => 
    array (
      'type' => 1,
    ),
    4 => 
    array (
      'module' => 'files',
      'action' => 'top',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'latestUpdates' => 
  array (
    0 => '/latest_updates/:page',
    1 => '#^/latest_updates(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'page',
    ),
    3 => 
    array (
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'info',
      'action' => 'latestupdates',
      'page' => 1,
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'homepage' => 
  array (
    0 => '/',
    1 => '/^[\\/]*$/',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'default',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default_symfony' => 
  array (
    0 => '/skyitech/:action/*',
    1 => '#^/skyitech(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'action',
    ),
    3 => 
    array (
      'action' => 1,
    ),
    4 => 
    array (
      'module' => 'default',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default_index' => 
  array (
    0 => '/:module',
    1 => '#^(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'module',
    ),
    3 => 
    array (
      'module' => 1,
    ),
    4 => 
    array (
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default' => 
  array (
    0 => '/:module/:action/*',
    1 => '#^(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'module',
      1 => 'action',
    ),
    3 => 
    array (
      'module' => 1,
      'action' => 1,
    ),
    4 => 
    array (
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
)
);
