<?php
// auto-generated by sfCacheConfigHandler
// date: 2017/08/31 18:14:43
$this->addCache($moduleName, '_category', array('withLayout' => false, 'lifeTime' => 600, 'clientLifeTime' => 600, 'contextual' => true, 'vary' => array ()));
$this->addCache($moduleName, '_updates', array('withLayout' => false, 'lifeTime' => 600, 'clientLifeTime' => 600, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'latestupdates', array('withLayout' => false, 'lifeTime' => 1800, 'clientLifeTime' => 1800, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'lastadded', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'top', array('withLayout' => false, 'lifeTime' => 60, 'clientLifeTime' => 60, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

