<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/12/01 10:52:45
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'gd_mime_type',
),
  'app_setorder' => true,
  'app_webpath' => 'http://frashmusic.club/mm-admin4589',
  'app_upload_dir' => 'http://frashmusic.club/siteuploads',
  'app_webmaster' => 'admin@frashmusic.club',
  'app_frontsiteurl' => 'http://frashmusic.club',
  'app_filename2hide' => '(frashmusic.club)',
  'app_sitename' => 'frashmusic.club',
));
