<?php
// auto-generated by sfCacheConfigHandler
// date: 2017/12/01 10:56:46
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

