<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/12/01 11:21:51
$this->security = array (
  'indexsuccess' => 
  array (
    'is_secure' => false,
  ),
  'captcha' => 
  array (
    'is_secure' => false,
  ),
  'logout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
);
