<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/12/01 10:55:14

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'hostspec' => 'localhost',
  'database' => 'getindia_skytech',
  'username' => 'getindia_skytech',
  'password' => '$w$[y)9CBj+K',
  'encoding' => 'utf8',
  'persistent' => false,
), 'propel');
$this->databases['propel'] = $database;
