<?php
// auto-generated by sfPropelCrud
// date: 2013/08/22 13:14:24
?>
<?php

/**
 * admin actions.
 *
 * @package    
 * @subpackage admin
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class adminActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('admin', 'list');
  }

  public function executeList()
  {
  	if($this->getUser()->getAttribute('ADMINSUPERADMIN','','admin')!='Y')
  		die('No Permission');
    $this->admins = AdminPeer::doSelect(new Criteria());
  }

  public function executeCreate()
  {
  	if($this->getUser()->getAttribute('ADMINSUPERADMIN','','admin')!='Y')
  		die('No Permission');
    $this->admin = new Admin();
    $this->admin->setIsSuperadmin('N');

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
  	if($this->getUser()->getAttribute('ADMINSUPERADMIN','','admin')!='Y')
  		die('No Permission');
    $this->admin = AdminPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->admin);
  }

  public function executeUpdate()
  {
  	if($this->getUser()->getAttribute('ADMINSUPERADMIN','','admin')!='Y')
  		die('No Permission');
    if (!$this->getRequestParameter('id'))
    {
      $admin = new Admin();
    }
    else
    {
      $admin = AdminPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($admin);
    }

    $admin->setId($this->getRequestParameter('id'));
    $admin->setUsername($this->getRequestParameter('username'));
    if($this->getRequestParameter('password'))
    	$admin->setPassword(md5($this->getRequestParameter('password')));
    $admin->setLevel($this->getRequestParameter('level'));
    $admin->setIsSuperadmin(strtoupper($this->getRequestParameter('is_superadmin')));

    $admin->save();

    return $this->redirect('admin/list');
  }

  public function executeDelete()
  {
  	if($this->getUser()->getAttribute('ADMINSUPERADMIN','','admin')!='Y')
  		die('No Permission');
    $admin = AdminPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($admin);

    $admin->delete();

    return $this->redirect('admin/list');
  }
}
