<?php
// auto-generated by sfPropelCrud
// date: 2009/11/13 18:39:30
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $updates->getId() ?></td>
</tr>
<tr>
<th>Description: </th>
<td><?php echo $updates->getDescription() ?></td>
</tr>
<tr>
<th>Status: </th>
<td><?php echo $updates->getStatus() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $updates->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'updates/edit?id='.$updates->getId()) ?>
&nbsp;<?php echo link_to('list', 'updates/list') ?>
