<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/08/31 22:02:34

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'hostspec' => 'localhost',
  'database' => 'bfmusic_in',
  'username' => 'bfmusic_in',
  'password' => 'uD$t^LPrccES',
  'encoding' => 'utf8',
  'persistent' => false,
), 'propel');
$this->databases['propel'] = $database;
