<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/08/31 22:02:34
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
        1 => 'level2',
        2 => 'level3',
      ),
    ),
  ),
);
