<?php
// auto-generated by sfCacheConfigHandler
// date: 2017/08/31 23:49:08
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

