<?php
// auto-generated by sfPropelCrud
// date: 2009/07/22 19:29:36
?>
<?php

/**
 * sites actions.
 *
 * @package    
 * @subpackage sites
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class deletezeroAction extends sfAction
{
  public function execute()
  {
		$c = new Criteria();
		$c->addSelectColumn(FilesPeer::ID);
		$c->add(FilesPeer::SIZE,0);
		$rs = FilesPeer::doSelectRs($c);
		foreach($rs as $k => $v)
		{
			echo $v[0]; continue;
	    $files = FilesPeer::retrieveByPk($v[0]);
	    $this->forward404Unless($files);

			$dataServer = 'sfd'.ceil($files->getId()/500);
			$thumbServer = 'sft'.ceil($files->getId()/500);

	   /*
	   * SKYiTech :: Remove folder & all files of this file
	   */
	   myUser::rmdirr(sfConfig::get('sf_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/');
		sfToolkit::clearGlob(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$files->getId().'_*.jpg');
	
	   $parentCategory = CategoryPeer::retrieveByPk($files->getCategoryId());
	   if(CategoryPeer::hasFiles($files->getCategoryId(),1)==1)
	   {
		    $parentCategory->setChild('N');
		    $parentCategory->save();
		}
	    $files->delete();
	  }
    return $this->redirect($_SERVER['HTTP_REFERER']);
    //return $this->redirect('files/list'.($this->getRequestParameter('cid') ? '?cid='.$this->getRequestParameter('cid') : ''));
  }

	public function handleError()
	{
 		deletezerosAction::execute();
 		return sfView::NONE;
	}

}
