<?php
// auto-generated by sfPropelCrud
// date: 2009/07/22 19:29:36
?>
<?php

/**
 * sites actions.
 *
 * @package    
 * @subpackage sites
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class deleteMultipleAction extends sfAction
{
  public function execute()
  {
  	if($this->getRequestParameter('ids') && ($this->getRequestParameter('commit')=='check' || $this->getRequestParameter('commit')=='delete')){
  	foreach(explode(chr(13),$this->getRequestParameter('ids')) as $id){
  	$id = trim($id);
//  	echo $id.'-';
    if($files = FilesPeer::retrieveByPk($id)){
	    $parentCategory = CategoryPeer::retrieveByPk($files->getCategoryId());
	    $parentsArray = explode('||',$parentCategory->getParentsArray());
	    $t='';
	    for($i = 2; $i<=count($parentsArray); $i+=2)
	    	$t .= $parentsArray[$i].' ... ';
    	$this->lastDeleteFile .= $id." - <b>".$files->getFileName()."</b> [cid:".$files->getCategoryId()." - ".$parentCategory->getCategoryName()."] - <b title='$t'><i>".@$parentsArray[2]."</i></b><br/>";
    }
   	else{
   		$this->lastFailFile .= "$id - Not Found<br/>";
   		continue;
   	}
    
//    $this->forward404Unless($files);
  	if($this->getRequestParameter('commit')!='delete')
  		continue;
    /*
    * SKYiTech :: Remove folder & all files of this file
    */
		$dataServer = 'sfd'.ceil($files->getId()/500);
		$thumbServer = 'sft'.ceil($files->getId()/500);
    myUser::rmdirr(sfConfig::get('sf_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/');

		//if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$files->getId().'_1.jpg'))
		{
			sfToolkit::clearGlob(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$files->getId().'_*.jpg');
		}

    if(CategoryPeer::hasFiles($files->getCategoryId(),1)==1)
    {
	    $parentCategory->setChild('N');
	    $parentCategory->save();
		}
		/*
		* SKYiTech :: updating file's count for this files parent categories
		*/
		myUser::updateFilesTotal($files->getCategoryId(),$parentCategory->getParents(),'remove',1);

    $files->delete();
    myUser::clearFileCache($id);
	  }
//    return $this->redirect($_SERVER['HTTP_REFERER']);
    //return $this->redirect('files/list'.($this->getRequestParameter('cid') ? '?cid='.$this->getRequestParameter('cid') : ''));
	  }
  }

	public function handleError()
	{
 		deleteMultipleAction::execute();
 		return sfView::NONE;
	}

}
