<?php
// auto-generated by sfPropelCrud
// date: 2009/07/22 19:29:36
?>
<?php

/**
 * sites actions.
 *
 * @package    
 * @subpackage sites
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class deletefileAction extends sfAction
{
  public function execute()
  {
    $files = FilesPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($files);

		$dataServer = 'sfd'.ceil($files->getId()/500);

		$type = $this->getRequestParameter('type');
		if(!in_array($type,array(64,192,320))){
			echo "Invalid Request";
			exit;
		}

		if( is_file( sfConfig::get('sf_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/'.myClass::MultiFileName($files->getFileName(),$type) ) ){
			unlink(sfConfig::get('sf_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/'.myClass::MultiFileName($files->getFileName(),$type) );
			echo "File Deleted Successfully";
		}
		return sfView::NONE;
		exit;
	}

}
