<?php
// auto-generated by sfPropelCrud
// date: 2009/07/22 19:29:36
?>
<?php

/**
 * sites actions.
 *
 * @package    
 * @subpackage sites
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class dirCatchAction extends sfAction
{
  public function execute()
  {
  	if(!$this->getRequestParameter('category_id'))
  		$this->redirect('category','list');

	  $this->parentCategory = CategoryPeer::retrieveByPk($this->getRequestParameter('category_id'));
  	$dirs = array();
  	$dir_name = array();
  	$files = array();
  	$rename_file_name = array();
 		$this->filesSelectedNow = false;
 		$this->dir_path = $this->getRequestParameter('dir_path');
 		$this->category_id = $this->getRequestParameter('category_id');
  	if($this->getRequestParameter('checkedFiles')){
  		foreach($this->getRequestParameter('checkedFiles') as $key => $value){
  			$files[] = $value;
  			$rename_file_name[] = $this->getRequestParameter('rename_'.md5($value));
  		}
  		$this->filesSelectedNow = true;
  	//print_r($files); exit;
  	}
  	elseif($this->getRequestParameter('dir_path')){
  		$dir = str_replace('http://'.$_SERVER['HTTP_HOST'].'/','',$this->getRequestParameter('dir_path'));
	  	$dir = $_SERVER['DOCUMENT_ROOT'].'/'.$dir;
	  	$replaceText = explode(',',$this->getRequestParameter('replaceText'));
	    if( $dh = opendir($dir))
	    {
	        while( false !== ($file = readdir($dh)))
	        {
	            if( $file == '.' || $file == '..' || substr($file,0,9) == '.htaccess' || substr($file,0,6) == 'thumb-')
	                continue;
	            $path = $dir . '/' . $file;
	            if( is_dir($path)){
	            	$dirs[] =  base64_encode(str_replace($_SERVER['DOCUMENT_ROOT'],sfConfig::get('app_frontsiteurl'), str_replace(' ','%20',$path)));
	            	$dir_name[] = base64_encode($file);
	            }
	            elseif(is_file($path)){
	                $files[str_replace($replaceText,'',$file)] = base64_encode(str_replace($_SERVER['DOCUMENT_ROOT'],sfConfig::get('app_frontsiteurl'), str_replace(' ','%20',$path)));
	                $rename_file_name[str_replace($replaceText,'',$file)] = base64_encode(str_replace($replaceText,'',$file));
	            }
	
	        }
	        closedir($dh);
	    }
  	}
  	asort($dirs);
		if($this->getRequestParameter('commit')=='show files Z-A'){
	  	krsort($files);
  		krsort($rename_file_name);
  	}
  	else{
	  	ksort($files);
  		ksort($rename_file_name);
  	}
	 	$this->dirs = $dirs;
	 	$this->dir_name = $dir_name;
	 	$this->files = $files;
	 	$this->rename_file_name = $rename_file_name;
	 	$this->replaceText = $this->getRequestParameter('replaceText');
	 	$this->removeFile = $this->getRequestParameter('removeFile');
	 	$this->mp3tags = $this->getRequestParameter('mp3tags');
  }

	public function handleError()
	{
 		dirCatchAction::execute();
 		return sfView::NONE;
	}

}
