<?php
// auto-generated by sfPropelCrud
// date: 2009/08/28 12:12:29
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $category->getId() ?></td>
</tr>
<tr>
<th>Category name: </th>
<td><?php echo $category->getCategoryName() ?></td>
</tr>
<tr>
<th>Url: </th>
<td><?php echo $category->getUrl() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $category->getTitle() ?></td>
</tr>
<tr>
<th>Description: </th>
<td><?php echo $category->getDescription() ?></td>
</tr>
<tr>
<th>Parents: </th>
<td><?php echo $category->getParents() ?></td>
</tr>
<tr>
<th>ParentsFull: </th>
<td><?php echo $category->getParentsarray() ?></td>
</tr>
<tr>
<th>Status: </th>
<td><?php echo $category->getStatus() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'category/edit?id='.$category->getId()) ?>
&nbsp;<?php echo link_to('list', 'category/list') ?>
