<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/09/01 16:17:28
sfConfig::add(array(
  'sf_logging_enabled' => false,
  'sf_logging_level' => 'debug',
  'sf_logging_rotate' => false,
  'sf_logging_period' => 7,
  'sf_logging_history' => 10,
  'sf_logging_purge' => true,
));
