<?php
// auto-generated by sfPropelCrud
// date: 2009/08/28 12:12:29
?>
<?php use_helper('Object') ?>

<?php echo form_tag('artist/delete') ?>

<?php echo input_hidden_tag('id', $id) ?>
<h1>Confirm Deleting Artist -> '<?php echo myUser::convert_name($artist->getName())?>' ??</h1>

<?php echo submit_tag('confirm delete') ?>
&nbsp;<?php echo link_to('Do not Delete', 'artist/list') ?>
</form>
