<?php use_helper('Javascript') ?>
<?php
// auto-generated by sfPropelCrud
// date: 2009/08/28 12:12:29
if($sf_params->get('msg'))
	echo '<h2 style="color:red; text-align:center;">'.$sf_params->get('msg').'</b></h2>';
?>
<?php use_helper('Object') ?>
<h1>Artist Editor</h1>
<?php include_partial('global/topAction'); ?>

<?php echo form_tag('artist/update',array('name'=>'Artist', 'enctype'=>'multipart/form-data')) ?>

<?php echo object_input_hidden_tag($artist, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Artist Name:</th>
  <td><?php echo object_input_tag($artist, 'getName', array ('size' => 60,)) ?></td>
</tr>
<tr>
	<th>Thumb display:</th>
	<td><?php
		if(is_file(sfConfig::get('sf_upload_dir').'/thumb/singer/'.myUser::convert_name($artist->getName()).'_rb.jpg')){
			echo '<div id="thumbUpdate">'.
			image_tag(sfConfig::get('app_upload_dir').'/thumb/singer/'.myUser::convert_name($artist->getName()).'_1.jpg').'&nbsp;'.
			image_tag(sfConfig::get('app_upload_dir').'/thumb/singer/'.myUser::convert_name($artist->getName()).'_2.jpg').'&nbsp;'.
			image_tag(sfConfig::get('app_upload_dir').'/thumb/singer/'.myUser::convert_name($artist->getName()).'_3.jpg').'&nbsp;'.
			image_tag(sfConfig::get('app_upload_dir').'/thumb/singer/'.myUser::convert_name($artist->getName()).'_4.jpg').'&nbsp;'.
			link_to('original',sfConfig::get('app_upload_dir').'/thumb/singer/'.myUser::convert_name($artist->getName()).'_rb.jpg').
			'</div>';
		}
			echo 'url:&nbsp;'.input_tag('thumb_url_path', '', array ('size'=>60));
			echo '&nbsp;'.input_file_tag('thumb_name',  array ('size' => 20,));
			echo '&nbsp;&nbsp;&nbsp;'.link_to_remote('Remove Thumb', array('update' => 'thumbUpdate',
																			    'url'    => 'artist/deletethumb?id='.$artist->getId(),));
			echo '<hr/>Watermark Position: ';
			echo radiobutton_tag('position','T').label_for('position_T',' Top').'&nbsp;&nbsp;';
			echo radiobutton_tag('position','M').label_for('position_M',' Middle').'&nbsp;&nbsp;';
			echo radiobutton_tag('position','B',true).label_for('position_B',' Bottom').'&nbsp;&nbsp;';
			echo checkbox_tag('position_force','yes').label_for('position_force',' Change Position Only');
		?></td>
</tr>
<tr>
  <th>Status:</th>
  <td><span class="activeDeactiveButton"><?php echo checkbox_tag('status', 'A', ($artist->getStatus()=='B'?false:true), array ('')) ?><span></span></span> Active / Block Artist</td>
</tr>
<tr>
  <th>Featured:</th>
  <td><span class="featureButton"><?php echo checkbox_tag('featured', 'F', ($artist->getStatus()=='F'?true:false), array ('')) ?><span></span></span> Add to Featured Artist</td>
</tr>

</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($artist->getId()): ?>
  &nbsp;<?php echo link_to('cancel', 'artist/list') ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'artist/list') ?>
<?php endif; ?>
</form>

<script type="text/javascript">
jQuery('.editor').dblclick(function(){
	CKEDITOR.replace( this );
});
</script>