<?php
// auto-generated by sfPropelCrud
// date: 2009/08/28 12:12:29
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $artist->getId() ?></td>
</tr>
<tr>
<th>Artist Name: </th>
<td><?php echo $artist->getName() ?></td>
</tr>
<tr>
<th>Status: </th>
<td><?php echo $artist->getStatus() ?></td>
</tr>

</tbody>
</table>
<hr />
<?php echo link_to('edit', 'artist/edit?id='.$artist->getId()) ?>
&nbsp;<?php echo link_to('list', 'artist/list') ?>
