<?php
// auto-generated by sfPropelCrud
// date: 2010/01/29 18:51:02
?>
<?php use_helper('Object') ?>

<?php echo form_tag('setting/changePassword') ?>

<?php echo object_input_hidden_tag($admin, 'getId') ?>

<table>
<tbody>
<tr>
	<th>Username*:</th>
	<td><?php echo input_tag('username', $admin->getUsername(), array ('size' => 50)); ?></td>
</tr>
<tr>
	<th>Password*:</th>
	<td><?php echo input_tag('password','', array ('size' => 50)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
&nbsp;<?php echo link_to('cancel', 'admin/list') ?>
</form>
