<?php
// auto-generated by sfPropelCrud
// date: 2009/08/10 18:07:49
?>
<?php use_helper('Object') ?>

<?php echo form_tag('setting/update') ?>

<?php echo object_input_hidden_tag($setting, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Meta:</th>
  <td><?php echo object_input_tag($setting, 'getMeta', array (
  'size' => 30,
)) ?></td>
</tr>
<tr>
  <th>Description:</th>
  <td><?php echo object_input_tag($setting, 'getDescription', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Value:</th>
  <td><?php echo object_input_tag($setting, 'getValue', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Device:</th>
  <td><?php echo object_input_tag($setting, 'getDevice', array (
  'size' => 50,
)) ?><br/>G: general<br/>M: mobile<br/>P: pc</td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($setting->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'setting/delete?id='.$setting->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'setting/show?id='.$setting->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'setting/list') ?>
<?php endif; ?>
</form>
