<?php
// auto-generated by sfPropelCrud
// date: 2009/08/10 18:07:49
?>
<?php use_helper('Javascript'); ?>
<h1>setting <?php echo $sf_params->get('device'); ?></h1>
<table>
<thead>
<tr>
  <th>Meta</th>
  <th>Value</th>
  <th>Description</th>
  <th>Device</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($settings as $setting): ?>
<tr class="setting_<?=$setting->getDevice()?>">
	<td><?php echo link_to($setting->getMeta(), 'setting/edit?id='.$setting->getId()) ?></td>
	<td><?php echo $setting->getValue() ?></td>
	<td><?php echo $setting->getDescription() ?></td>
	<td><?php echo $setting->getDevice() ?></td>
	<td><?php echo $setting->getUpdatedAt() ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
