<?php
// auto-generated by sfPropelCrud
// date: 2009/08/10 18:07:49
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $setting->getId() ?></td>
</tr>
<tr>
<th>Meta: </th>
<td><?php echo $setting->getMeta() ?></td>
</tr>
<tr>
<th>Description: </th>
<td><?php echo $setting->getDescription() ?></td>
</tr>
<tr>
<th>Value: </th>
<td><?php echo $setting->getValue() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $setting->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'setting/edit?id='.$setting->getId()) ?>
&nbsp;<?php echo link_to('list', 'setting/list') ?>
