<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/12 15:28:55
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'gd_mime_type',
),
  'app_setorder' => true,
  'app_webpath' => 'http://mp3fun.tk/mm-admin4589',
  'app_upload_dir' => 'http://mp3fun.tk/siteuploads',
  'app_webmaster' => 'admin@mp3fun.tk',
  'app_frontsiteurl' => 'http://mp3fun.tk',
  'app_filename2hide' => '(mp3fun.tk)',
  'app_sitename' => 'mp3fun.tk',
));
