<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/11/12 15:34:13
$this->security = array (
  'list' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
      ),
    ),
  ),
  'create' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
      ),
    ),
  ),
  'edit' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
      ),
    ),
  ),
  'update' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
      ),
    ),
  ),
  'delete' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
      ),
    ),
  ),
  'changepassword' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
        1 => 'level2',
        2 => 'level3',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
      ),
    ),
  ),
);
