<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/11/12 15:33:49
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
      ),
    ),
  ),
);
