<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/12 15:28:56
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
