<?php
// auto-generated by sfPropelCrud
// date: 2009/12/16 17:37:21
?>
<?php use_helper('Object') ?>

<?php echo form_tag('loghistory/update') ?>

<?php echo object_input_hidden_tag($log_history, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Date:</th>
  <td><?php echo object_input_tag($log_history, 'getDate', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Host:</th>
  <td><?php echo object_input_tag($log_history, 'getHost', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Hits:</th>
  <td><?php echo object_input_tag($log_history, 'getHits', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Download:</th>
  <td><?php echo object_input_tag($log_history, 'getDownload', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Files:</th>
  <td><?php echo object_input_tag($log_history, 'getFiles', array (
  'size' => 150,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($log_history->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'loghistory/delete?id='.$log_history->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'loghistory/show?id='.$log_history->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'loghistory/list') ?>
<?php endif; ?>
</form>
