<?php
// auto-generated by sfPropelCrud
// date: 2009/12/16 17:37:21
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $log_history->getId() ?></td>
</tr>
<tr>
<th>Date: </th>
<td><?php echo $log_history->getDate() ?></td>
</tr>
<tr>
<th>Host: </th>
<td><?php echo $log_history->getHost() ?></td>
</tr>
<tr>
<th>Download: </th>
<td><?php echo $log_history->getDownload() ?></td>
</tr>
<tr>
<th>Files: </th>
<td><?php echo $log_history->getFiles() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'loghistory/edit?id='.$log_history->getId()) ?>
&nbsp;<?php echo link_to('list', 'loghistory/list') ?>
