<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/09/01 16:31:32

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'hostspec' => 'localhost',
  'database' => 'djallx5e_maza',
  'username' => 'djallx5e_maza',
  'password' => 'qxoivNVN&puR',
  'encoding' => 'utf8',
  'persistent' => false,
), 'propel');
$this->databases['propel'] = $database;
