<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/09/01 16:31:32
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'gd_mime_type',
),
  'app_setorder' => true,
  'app_webpath' => 'http://djallmaza.in/mm-admin4589',
  'app_upload_dir' => 'http://djallmaza.in/siteuploads',
  'app_webmaster' => 'admin@djallmaza.in',
  'app_frontsiteurl' => 'http://djallmaza.in',
  'app_filename2hide' => '(DjAllMaza.In)',
  'app_sitename' => 'DjAllMaza.In',
));
