<?php
// auto-generated by sfValidatorConfigHandler
// date: 2017/09/01 16:31:32

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validatorManager->registerName('username', 1, 'The username field cannot be left blank', null, null, false);
  $validatorManager->registerName('password', 1, 'The password field cannot be left blank', null, null, false);
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
