<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/09/01 16:35:00
$this->security = array (
  'create' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
        1 => 'level2',
        2 => 'level3',
      ),
    ),
  ),
  'edit' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
        1 => 'level2',
        2 => 'level3',
      ),
    ),
  ),
  'update' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
        1 => 'level2',
        2 => 'level3',
      ),
    ),
  ),
  'delete' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
        1 => 'level2',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'level1',
        1 => 'level2',
        2 => 'level3',
      ),
    ),
  ),
);
