default:
  is_secure: on
  credentials: [[ level1 ]]

list:
  is_secure: on
  credentials: [[ level1 ]]

create:
  is_secure: on
  credentials: [[ level1 ]]

edit:
  is_secure: on
  credentials: [[ level1 ]]

update:
  is_secure: on
  credentials: [[ level1 ]]

delete:
  is_secure: on
  credentials: [[ level1 ]]

changePassword:
  is_secure: on
  credentials: [[ level1, level2, level3 ]]

