<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/12 15:17:06
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'gd_mime_type',
),
  'app_webpath' => '/',
  'app_sitename' => 'mp3fun.tk',
  'app_smallname' => 'mp3fun',
  'app_filename2hide' => '(mp3fun.tk)',
  'app_onlinetime' => 600,
));
