<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/11/12 15:17:06

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'hostspec' => 'localhost',
  'database' => 'mpfuntk_mp3fun',
  'username' => 'mpfuntk_mp3fun',
  'password' => 'G$CS0e$@lb2Z',
  'encoding' => 'utf8',
  'persistent' => false,
), 'propel');
$this->databases['propel'] = $database;
