<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/01/19 06:44:06

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'hostspec' => 'localhost',
  'database' => 'mp3nagpu_munna',
  'username' => 'mp3nagpu_munna',
  'password' => 'D^aL_[QCawHE',
  'encoding' => 'utf8',
  'persistent' => false,
), 'propel');
$this->databases['propel'] = $database;
