<?php
// auto-generated by sfPropelCrud
// date: 2009/08/28 17:35:10
?>
<h1>Delete Multiple</h1>
<?php use_helper('Object','Javascript') ?>
<?php echo form_tag('files/deleteMultiple',array('name'=>'Files', 'enctype'=>'multipart/form-data')) ?>

<?php
if(isset($lastDeleteFile))
	echo '<div class="msg done">Files Available<br/>'.$lastDeleteFile.'</div>';
if(isset($lastFailFile))
	echo '<div class="msg error">Files Not Available..<br/>'.$lastFailFile.'</div>';
?>
<table>
<tbody>
<tr>
  <th>Ids to Delete:</th>
  <td>
  	<?php echo textarea_tag('ids',@$sf_params->get('ids'),array('size'=>'60x4'));?>
  </td>
</tr>
</tbody>
</table>
<hr />
<?php 
echo submit_tag('check',array('title'=>'Click to check for files status'));
echo submit_tag('delete',array('confirm'=>'Are You Sure??'));
?>
</form>
