<?php
// auto-generated by sfPropelCrud
// date: 2009/08/28 17:35:10
?>
<h1>File Uploader -> <?php echo $files->getFileName() ?></h1>
<?php include_partial('global/topAction',array('id' => $files->getId())); ?>
<?php if($files->getCategoryId())
	include_partial('global/catpath',array('parents' => CategoryPeer::retrieveByPk($files->getCategoryId()),'self'=>true));
?>
<hr />
<?php
	$dataServer = 'sfd'.ceil($files->getId()/500);
	$thumbServer = 'sft'.ceil($files->getId()/500);
if($files->getId()){
	echo link_to('[[ fileLocation ]]',sfConfig::get('app_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/'.$files->getFileName(),array('target'=>'_blank'));
}
?>
<?php use_helper('Object','Javascript','Validation') ?>
<?php echo form_tag('files/update',array('name'=>'Files', 'enctype'=>'multipart/form-data')) ?>

<?php echo object_input_hidden_tag($files, 'getId') ?>
<?php echo input_hidden_tag('category_id', $files->getCategoryId()) ?>
<?php
if(isset($lastFile))
	echo '<div class="msg done">Last file : '.$lastFile.'</div>';
?>
<table>
<tbody>
<tr>
	<th>File / URL:</th>
	<td><?php echo form_error('file_name') ?>
		<div>
		<?php
				echo 'url to upload:&nbsp;'.input_tag('url_path', $files->getUrl(), array ('size'=>60,'onblur'=>'var tt=this.value; tt = tt.split("/"); tt=tt.pop();document.getElementById(\'rename_file_name\').value=tt;checkname();'));
				echo '<br />&nbsp;'.checkbox_tag('urlType', 'CopyToServer', ($files->getExtension()=='URL'?false:true) );
				echo label_for('urlType',' Click to copy file to our server');
		?>
		</div>
		<div>
		<?php
				echo 'New File:&nbsp;'.input_file_tag('file_name',  array ('size' => 20,'onchange'=>'document.getElementById(\'rename_file_name\').value=this.value;checkname();'));
		?>
		</div><hr />
		<?php
				echo 'Rename:&nbsp;'.input_tag('rename_file_name', $files->getFileName(), array ('size'=>60));
		?><span id="uni_name"></span>
		<script type="text/javascript">
		function checkname(){
			var oldname="<?php echo myUser::fileName($files->getFileName()) ?>";
			if(oldname){
			if(oldname != document.getElementById('rename_file_name').value){
				document.getElementById('uni_name').innerHTML='name changed | org name = <?php echo myUser::fileName($files->getFileName()) ?>';
				document.getElementById('uni_name').className='msg warning';
			}
			else{
				document.getElementById('uni_name').innerHTML= 'name are perfect';
				document.getElementById('uni_name').className='msg done';
			}
			}
		}	
		</script>
		</td>
</tr>
<?php if($files->getExtension()=='MP3'): ?>
<tr>
	<th>Multiple Format:</th>
	<td>
		<h3>64 kbps <?php
							if(is_file(sfConfig::get('sf_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/'.myClass::MultiFileName($files->getFileName(),'64'))){
					echo '<span id="file64">';
					echo link_to('[_changeTag_]',sfConfig::get('app_webpath').'/changeMp3.php?Filename='.sfConfig::get('sf_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/'.myClass::MultiFileName($files->getFileName(),'64'),array('target'=>'_blank'));
					echo ' '.link_to('[_fileLocation_]',sfConfig::get('app_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/'.myClass::MultiFileName($files->getFileName(),'64'),array('target'=>'_blank'));
					echo '&nbsp;&nbsp;&nbsp;'.link_to_remote(image_tag('delete').'Remove', array('update' => 'file64',
																					    'url'    => 'files/deletefile?type=64&id='.$files->getId(),));
					echo '</span>';
				}
?></h3>
		<?php echo form_error('file_name2') ?>
		<div>
		<?php
				echo 'url:&nbsp;'.input_tag('url_path2', $files->getUrl(), array ('size'=>30));
				echo ' /OR/ Upload:&nbsp;'.input_file_tag('file_name2',  array ('size' => 20));
		?>
		</div>
		<hr />
		<h3>192 kbps <?php
							if(is_file(sfConfig::get('sf_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/'.myClass::MultiFileName($files->getFileName(),'192'))){
					echo '<span id="file192">';
					echo link_to('[_changeTag_]',sfConfig::get('app_webpath').'/changeMp3.php?Filename='.sfConfig::get('sf_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/'.myClass::MultiFileName($files->getFileName(),'192'),array('target'=>'_blank'));
					echo ' '.link_to('[_fileLocation_]',sfConfig::get('app_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/'.myClass::MultiFileName($files->getFileName(),'192'),array('target'=>'_blank'));
					echo '&nbsp;&nbsp;&nbsp;'.link_to_remote(image_tag('delete').'Remove', array('update' => 'file192',
																					    'url'    => 'files/deletefile?type=192&id='.$files->getId(),));
					echo '</span>';
				}
?></h3>
		<?php echo form_error('file_name3') ?>
		<div>
		<?php
				echo 'url:&nbsp;'.input_tag('url_path3', $files->getUrl(), array ('size'=>30));
				echo ' /OR/ Upload:&nbsp;'.input_file_tag('file_name3',  array ('size' => 20));
		?>
		</div>
		<hr />
		<h3>320 kbps <?php
				if(is_file(sfConfig::get('sf_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/'.myClass::MultiFileName($files->getFileName(),'320'))){
					echo '<span id="file320">';
					echo link_to('[_changeTag_]',sfConfig::get('app_webpath').'/changeMp3.php?Filename='.sfConfig::get('sf_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/'.myClass::MultiFileName($files->getFileName(),'320'),array('target'=>'_blank'));
					echo ' '.link_to('[_fileLocation_]',sfConfig::get('app_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/'.myClass::MultiFileName($files->getFileName(),'320'),array('target'=>'_blank'));
					echo '&nbsp;&nbsp;&nbsp;'.link_to_remote(image_tag('delete').'Remove', array('update' => 'file320',
																					    'url'    => 'files/deletefile?type=320&id='.$files->getId(),));
					echo '</span>';
				}
?></h3>
		<?php echo form_error('file_name4') ?>
		<div>
		<?php
				echo 'url:&nbsp;'.input_tag('url_path4', $files->getUrl(), array ('size'=>30));
				echo ' /OR/ Upload:&nbsp;'.input_file_tag('file_name4',  array ('size' => 20));
		?>
		</div>
		</td>
</tr>
<?php endif; ?>
<tr>
	<th>Thumb display:</th>
	<td><?php
				if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$files->getId().'_1.jpg')){
					echo '<div id="thumbUpdate">';
					for($i=1; $i<=8; $i++)
						echo image_tag(sfConfig::get('app_upload_dir').'/thumb/'.$thumbServer.'/'.$files->getId().'_'.$i.'.jpg',array('alt'=>'')).'&nbsp;';

					if(is_file(sfConfig::get('sf_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/thumb-'.$files->getId().'.jpg'))
						echo link_to('[Original]', sfConfig::get('app_upload_dir').'/files/'.$dataServer.'/'.$files->getId().'/thumb-'.$files->getId().'.jpg', 'target=_blank');

					echo '</div>';
				}

				if($files->getExtension()!='JPG' && $files->getExtension()!='PNG'){
					echo 'url:&nbsp;'.input_tag('thumb_url_path', '', array ('size'=>60));
					echo '<br/>Choose from PC:'.input_file_tag('thumb_name',  array ('size' => 20,));
					echo '&nbsp;&nbsp;&nbsp;'.link_to_remote('Remove Thumb', array('update' => 'thumbUpdate',
																					    'url'    => 'files/deletethumb?id='.$files->getId(),));
				}
		?></td>
</tr>
<!-- tr>
  <th>Category:</th>
  <td id="categoryIdDiv"><?php
  	echo javascript_tag(
		  remote_function(array(
		    'update'  => 'categoryIdDiv',
		    'url'     => 'category/getpath?id='.$files->getCategoryId(),
		  ))
		) ?>
  </td>
</tr -->
<tr>
  <th>Description:</th>
  <td><?php echo object_textarea_tag($files, 'getDescription',array('class'=>'editor','size'=>'60x2')); ?></td>
</tr>
<tr>
  <th>Singer:</th>
  <td><?php // echo object_textarea_tag($files, 'getSinger',array('class'=>'','size'=>'60x2')); 
  	?>
  	<input type="text" id="tags-input-local" name="singer" />
    <script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery("#tags-input-local").tokenInput([
        <?php
        	include($_SERVER['DOCUMENT_ROOT'].'/siteuploads/artistList.dat');
        ?>
        ],{
            prePopulate: [
        	<?php
        		if($files->getSinger())
        		foreach(explode(',',$files->getSinger()) as $tRow)
	        		if($tRow)
  	      			echo '{id: "'.$tRow.'", name: "'.$tRow.'"},
        			';
        	?>
            ],
            preventDuplicates: true,
        	});
    });
    </script>
   </td>
</tr>
<tr>
  <th>Tags:</th>
  <td><?php echo object_textarea_tag($files, 'getTags',array('class'=>'','size'=>'60x2')); ?></td>
</tr>
<?php if($sf_context->getActionName()!='create'): ?>
<tr>
  <th>Other:</th>
  <td>Size: <?php echo object_input_tag($files, 'getSize', array ()) ?>
  	Download: <?php echo object_input_tag($files, 'getDownload', array ('size' => 7,)) ?>
  	Extension: <?php echo object_input_tag($files, 'getExtension', array ('size' => 5,)) ?>
  	Order: <?php echo object_input_tag($files, 'getOrd', array ('size' => 3,)) ?></td>
</tr>
<?php endif; ?>
<tr>
  <th>Status:</th>
  <td><span class="activeDeactiveButton"><?php echo checkbox_tag('status', 'A', ($files->getStatus()=='B'?false:true), array ('')) ?><span></span></span> Active / Block File</td>
</tr>
<tr>
  <th>Featured:</th>
  <td><span class="featureButton"><?php echo checkbox_tag('featured', 'F', ($files->getStatus()=='F'?true:false), array ('')) ?><span></span></span> Add to Featured File</td>
</tr>
<tr>
  <th>MP3 Tags:</th>
  <td><?php echo checkbox_tag('mp3tags', 'true', true, (SETTING_MP3TAG_OVERWRITE=='ON' ? true : false), array ('')) ?> Overwrite MP3 Tags ?</td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($files->getId()): ?>
  &nbsp;<?php echo link_to('cancel', 'files/list?cid='.$files->getCategoryId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'files/list') ?>
<?php endif; ?>
</form>

<br/>
<?php if($sf_params->get('action')=='edit'){ ?>
<?php echo form_tag('files/moveid',array('name'=>'Files', 'enctype'=>'multipart/form-data')) ?>
<h1>Change Category</h1>
<table>
<tr>
<th rowspan=3 width=200>Target Category Id:</th>
<td>
	<?php echo object_input_hidden_tag($files, 'getId') ?>
	<?php echo input_tag('movetoid', $sf_params->get('movetoid')) ?>
		<input type="button" value="Check Path">
</td></tr><tr><td>
	<b>Path: </b><span id="targetCategoryPath"></span>
	<?php echo observe_field('movetoid', array(
	    'update'   => 'targetCategoryPath',
	    'url'      => 'category/getpath',
	    'with'     => "'id=' + value",
	    'loading'  => visual_effect('highlight', 'targetCategoryPath')
	)) ?>
</td></tr><tr><td>
<?php echo submit_tag('Move',array('onclick'=>'return confirm("sure to move?")')) ?>
</td></tr></table>
</form>
<?php } ?>