<?php
// auto-generated by sfPropelCrud
// date: 2009/08/28 17:35:10
?>
<h1>Show File -> <?php echo $files->getFileName() ?></h1>
<?php include_partial('global/topAction',array('id'=>$files->getId(),'pid' => $files->getCategoryId())); ?>
<?php if($files->getCategoryId())
	include_partial('global/catpath',array('parents' => CategoryPeer::retrieveByPk($files->getCategoryId()),'self'=>true));
?>

<table>
<tbody>
<tr>
<th>Preview: </th>
<td>
	<?php
		$thumbServer = 'sft'.ceil($files->getId()/500);
		$dataServer = 'sfd'.ceil($files->getId()/500);
		if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/small_'.$files->getId().'.jpg'))
			echo image_tag(sfConfig::get('app_upload_dir').'/thumb/'.$thumbServer.'/small_'.$files->getId().'.jpg');
		if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/animate_'.$files->getId().'.gif'))
			echo image_tag(sfConfig::get('app_upload_dir').'/thumb/'.$thumbServer.'/animate_'.$files->getId().'.gif');
	?>
</td>
</tr>
<tr>
<th>Id: </th>
<td><?php echo $files->getId() ?></td>
</tr>
<tr>
<th>File name: </th>
<td><?php echo $files->getFileName() ?></td>
</tr>
<tr>
<th>Category: </th>
<td><?php echo CategoryPeer::getCategoryName($files->getCategoryId()) ?></td>
</tr>
<tr>
<th>Size: </th>
<td><?php echo myClass::formatsize($files->getSize()) ?></td>
</tr>
<tr>
<th>Download: </th>
<td><?php echo $files->getDownload() ?></td>
</tr>
<tr>
<th>Extension: </th>
<td><?php echo $files->getExtension() ?></td>
</tr>
<tr>
<th>Status: </th>
<td><?php echo $files->getStatus() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $files->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
&nbsp;<?php echo link_to('[delete]'.image_tag('delete'), 'files/delete?id='.$files->getId().'&cid='.$files->getCategoryId()) ?>
&nbsp;&nbsp;<?php echo link_to('[edit]'.image_tag('edit'), 'files/edit?id='.$files->getId()) ?>
&nbsp;&nbsp;<?php echo link_to('[list]'.image_tag('list'), 'files/list') ?>
